question_data = [
                     {"type": "boolean",
                      "difficulty": "easy",
                      "category": "Science: Computers",
                      "question": "The programming language 'Python' is based off a modified version of 'JavaScript';.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "The Windows ME operating system was released in the year 2000.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "Ada Lovelace is often considered the first computer programmer.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
                      "incorrect_answers": ["False"]}
]
